<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="5" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Test is Start:Test]]>
    </line>
    <line>
      <![CDATA[Test is Start:verify_Homepage]]>
    </line>
    <line>
      <![CDATA[hi]]>
    </line>
    <line>
      <![CDATA[Test is Skipped:verify_Homepage]]>
    </line>
    <line>
      <![CDATA[Test is Start:verify_Homepage]]>
    </line>
    <line>
      <![CDATA[hi]]>
    </line>
    <line>
      <![CDATA[Test is Skipped:verify_Homepage]]>
    </line>
    <line>
      <![CDATA[Test is Start:verify_Homepage]]>
    </line>
    <line>
      <![CDATA[hi]]>
    </line>
    <line>
      <![CDATA[Test is Skipped:verify_Homepage]]>
    </line>
    <line>
      <![CDATA[Test is Start:verify_Homepage]]>
    </line>
    <line>
      <![CDATA[hi]]>
    </line>
    <line>
      <![CDATA[<a href='F:\selenium\Amezon.qa\.\Screenshorts\failure_screenshots\verify_Homepage_08_05_2018_10_35_44.png'> <img src='F:\selenium\Amezon.qa\.\Screenshorts\failure_screenshots\verify_Homepage_08_05_2018_10_35_44.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[Test is Start:verify_Homepage_HeaderLink_options]]>
    </line>
    <line>
      <![CDATA[Test is Success:verify_Homepage_HeaderLink_options]]>
    </line>
    <line>
      <![CDATA[<a href='F:\selenium\Amezon.qa\.\Screenshorts\pass__screenshots\verify_Homepage_HeaderLink_options_08_05_2018_10_36_49.png'> <img src='F:\selenium\Amezon.qa\.\Screenshorts\pass__screenshots\verify_Homepage_HeaderLink_options_08_05_2018_10_36_49.png' height='100' width='100'/> </a>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="162166" started-at="2018-05-08T17:04:09Z" finished-at="2018-05-08T17:06:51Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="162166" started-at="2018-05-08T17:04:09Z" finished-at="2018-05-08T17:06:51Z">
      <class name="Amazon.QA.Testcase.Homepage">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:Amazon.QA.Testcase.Homepage@837a77]" name="openBrowser" is-config="true" duration-ms="82657" started-at="2018-05-08T17:04:09Z" finished-at="2018-05-08T17:05:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="SKIP" signature="verify_Homepage()[pri:0, instance:Amazon.QA.Testcase.Homepage@837a77]" name="verify_Homepage" duration-ms="6090" started-at="2018-05-08T17:05:32Z" finished-at="2018-05-08T17:05:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true],
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true],
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Amazon.QA.Testcase.Homepage.verify_Homepage(Homepage.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test is Start:verify_Homepage]]>
            </line>
            <line>
              <![CDATA[hi]]>
            </line>
            <line>
              <![CDATA[Test is Skipped:verify_Homepage]]>
            </line>
          </reporter-output>
        </test-method> <!-- verify_Homepage -->
        <test-method status="SKIP" signature="verify_Homepage()[pri:0, instance:Amazon.QA.Testcase.Homepage@837a77]" name="verify_Homepage" duration-ms="2019" started-at="2018-05-08T17:05:38Z" finished-at="2018-05-08T17:05:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Amazon.QA.Testcase.Homepage.verify_Homepage(Homepage.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test is Start:verify_Homepage]]>
            </line>
            <line>
              <![CDATA[hi]]>
            </line>
            <line>
              <![CDATA[Test is Skipped:verify_Homepage]]>
            </line>
          </reporter-output>
        </test-method> <!-- verify_Homepage -->
        <test-method status="SKIP" signature="verify_Homepage()[pri:0, instance:Amazon.QA.Testcase.Homepage@837a77]" name="verify_Homepage" duration-ms="2203" started-at="2018-05-08T17:05:40Z" finished-at="2018-05-08T17:05:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Amazon.QA.Testcase.Homepage.verify_Homepage(Homepage.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test is Start:verify_Homepage]]>
            </line>
            <line>
              <![CDATA[hi]]>
            </line>
            <line>
              <![CDATA[Test is Skipped:verify_Homepage]]>
            </line>
          </reporter-output>
        </test-method> <!-- verify_Homepage -->
        <test-method status="FAIL" signature="verify_Homepage()[pri:0, instance:Amazon.QA.Testcase.Homepage@837a77]" name="verify_Homepage" duration-ms="1834" started-at="2018-05-08T17:05:42Z" finished-at="2018-05-08T17:05:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true],
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Amazon.QA.Testcase.Homepage.verify_Homepage(Homepage.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test is Start:verify_Homepage]]>
            </line>
            <line>
              <![CDATA[hi]]>
            </line>
            <line>
              <![CDATA[<a href='F:\selenium\Amezon.qa\.\Screenshorts\failure_screenshots\verify_Homepage_08_05_2018_10_35_44.png'> <img src='F:\selenium\Amezon.qa\.\Screenshorts\failure_screenshots\verify_Homepage_08_05_2018_10_35_44.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- verify_Homepage -->
        <test-method status="PASS" signature="verify_Homepage_HeaderLink_options()[pri:0, instance:Amazon.QA.Testcase.Homepage@837a77]" name="verify_Homepage_HeaderLink_options" duration-ms="61473" started-at="2018-05-08T17:05:48Z" finished-at="2018-05-08T17:06:49Z">
          <reporter-output>
            <line>
              <![CDATA[Test is Start:verify_Homepage_HeaderLink_options]]>
            </line>
            <line>
              <![CDATA[Test is Success:verify_Homepage_HeaderLink_options]]>
            </line>
            <line>
              <![CDATA[<a href='F:\selenium\Amezon.qa\.\Screenshorts\pass__screenshots\verify_Homepage_HeaderLink_options_08_05_2018_10_36_49.png'> <img src='F:\selenium\Amezon.qa\.\Screenshorts\pass__screenshots\verify_Homepage_HeaderLink_options_08_05_2018_10_36_49.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- verify_Homepage_HeaderLink_options -->
        <test-method status="PASS" signature="closebrowser()[pri:0, instance:Amazon.QA.Testcase.Homepage@837a77]" name="closebrowser" is-config="true" duration-ms="1045" started-at="2018-05-08T17:06:50Z" finished-at="2018-05-08T17:06:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
      </class> <!-- Amazon.QA.Testcase.Homepage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
